---
# tasks file for kubernetes-common role - Container Runtime and Kube Tools

- name: Install prerequisite packages
  ansible.builtin.apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl']
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository for containerd.io
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install containerd.io and create config file
  block:
    - name: Install containerd.io package
      ansible.builtin.apt:
        name: containerd.io
        state: present
        update_cache: yes
    - name: Create containerd config directory
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
    - name: Configure containerd and set runc as default runtime
      ansible.builtin.copy:
        dest: /etc/containerd/config.toml
        content: |
          version = 2
          [plugins."io.containerd.grpc.v1.cri".containerd]
            default_runtime_name = "runc"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              runtime_type = "io.containerd.runc.v2"
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                SystemdCgroup = true
      notify: Restart containerd

- name: Add Kubernetes GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
    state: present

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
    state: present
    filename: kubernetes

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name: ['kubelet=1.31.*', 'kubeadm=1.31.*', 'kubectl=1.31.*']
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: ['kubelet', 'kubeadm', 'kubectl']