# terraform/inventory.tpl
all:
  children:
    k8s_cluster:
      children:
        kube_control_plane:
          hosts:
            192.168.1.120:
            192.168.1.121:
            192.168.1.122:
        kube_node:
          hosts:
            192.168.1.130:
            192.168.1.131:
            192.168.1.132:
        etcd:
          hosts:
            192.168.1.120:
            192.168.1.121:
            192.168.1.122:
    loadbalancer:
      hosts:
        192.168.1.140:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'