# ansible/roles/kubernetes-common/tasks/main.yml
---
- name: Add Kubernetes GPG key from local repository
  apt_key:
    url: "http://{{ hostvars[groups['repository'][0]]['ansible_default_ipv4']['address'] }}/kubernetes/Release.key"
    state: present
  when: groups['repository'] is defined and groups['repository']|length > 0

- name: Add Kubernetes GPG key from internet (fallback)
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    state: present
  when: groups['repository'] is not defined or groups['repository']|length == 0

- name: Add Kubernetes repository (local)
  apt_repository:
    repo: "deb http://{{ hostvars[groups['repository'][0]]['ansible_default_ipv4']['address'] }}/kubernetes/deb/ /"
    state: present
  when: groups['repository'] is defined and groups['repository']|length > 0

- name: Add Kubernetes repository (internet fallback)
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
  when: groups['repository'] is not defined or groups['repository']|length == 0

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet=1.28.*
      - kubeadm=1.28.*
      - kubectl=1.28.*
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Start and enable kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
